DECLARE		@COLUMNS VARCHAR(8000)
DECLARE 	@TABLE VARCHAR(50)
SET		@TABLE = [INSERT TABLE NAME HERE IN '' REMOVE BRACKETS]
SET		@COLUMNS = ''
SELECT		@COLUMNS = @COLUMNS + NAME + '	' FROM SYSCOLUMNS
WHERE		ID = OBJECT_ID(@TABLE)
ORDER BY 	COLID
SELECT 		@COLUMNS